### ISSUE TITLE
Did you find a way of doing this in Spring Boot 2.0?

### ISSUE THREAD

**Issue by guxlightyear** [piomin/sample-spring-graphite#1]
https://github.com/piomin/sample-spring-graphite/blob/aaac85442c2b37e1e24c970de7c055bef8651dee/src/main/java/pl/piomin/graphite/GraphiteApplication.java#L19

My apologies for the approach, and for opening an issue in your repo, I just couldn't find any other way to leave a comment :)

I am trying to do something very similar, porting an Spring Boot 1.5 application into 2.0, and found that some of the key classes and interfaces are missing.

I bumped into this repository while investigating possible solutions, so thought to ping you and check if you had had any success.

By the way, feel free to close this issue, as it doesn't add any value to your repo.

**Comment by piomin** [comment]
yes, resolved in the latest version
